sonar.projectKey=python-ci-project
sonar.projectName=Python CI Project
sonar.projectVersion=1.0

sonar.sources=app
sonar.tests=tests
sonar.language=py
sonar.sourceEncoding=UTF-8

# nécessaire si vous utilisez un scanner installé dans Jenkins
